FROM fpm-base

# Compiles custom perl to it's prefix

RUN yum install -y gcc make perl patch

run curl -L https://raw.githubusercontent.com/tokuhirom/Perl-Build/master/perl-build | perl - 5.34.0 /opt/custom_perl/

